# Generated by Django 5.0.2 on 2024-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user@mail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
